name: Docker Images

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  images:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Cache target
        uses: actions/cache@v2
        with:
          path: |
            target/
          key: ${{ runner.os }}-release-${{ hashFiles('Cargo.lock') }}

      - name: Get stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Move binary
        run: |
          mv target/release/unflwrs unflwrs

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: unflwrs
          path: |
            unflwrs

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/syfaro/unflwrs

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
